version: "3.8"
services:
  shopware:
    image: dockware/dev:6.5.2.1
    container_name: BuildIT_RecentlyViewedPerformance
    ports:
      - "80"
      - "3306"
      - "22"
      - "8888"
      - "9999"
    volumes:
      - "./src:/var/www/html/custom/plugins/BuildIT_RecentlyViewedPerformance"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=1
networks:
  web:
    name: web
    driver: bridge
    external: true

